name=Talking_Display
version=1.0
author=Gerald Lechner
maintainer=Gerald Lechner
sentence=A library to output date, time and sensor values as speech.
paragraph=The library uses the library ESP8266Audio. The speach output is based on MP3 files. Files can be stored in LittleFS file system. No SD card is required.
category=Other
url=https://github.com/GerLech/Talking_Display
architectures=esp32
depends=ESP8266Audio
